"""add_task_name_field

Revision ID: 8b8d063ff7d8
Revises: c650bd4e5d7b
Create Date: 2025-04-21 07:06:57.262184+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b8d063ff7d8"
down_revision: Union[str, None] = "c650bd4e5d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
