"""add_cost_time

Revision ID: 866db2a5da03
Revises: 628ae42e8cde
Create Date: 2025-04-28 10:24:41.973716+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "866db2a5da03"
down_revision: Union[str, None] = "628ae42e8cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_logs",
        sa.Column(
            "cost_time", sa.Float(), nullable=True, comment="执行耗时（秒）"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_logs", "cost_time")
    # ### end Alembic commands ###
