"""add_password

Revision ID: f85bdec7ed66
Revises: 866db2a5da03
Create Date: 2025-04-29 09:10:16.666854+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f85bdec7ed66"
down_revision: Union[str, None] = "866db2a5da03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connections", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column(
            "password",
            mysql.VARCHAR(collation="utf8mb4_general_ci", length=100),
            nullable=False,
            comment="密码",
        ),
    )
    # ### end Alembic commands ###
