"""add_password

Revision ID: 5099715a1bca
Revises: f85bdec7ed66
Create Date: 2025-04-29 09:22:10.030961+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5099715a1bca"
down_revision: Union[str, None] = "f85bdec7ed66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column(
            "password_encrypted",
            sa.String(length=200),
            nullable=False,
            comment="加密密码",
        ),
    )
    op.drop_column("connections", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column(
            "password",
            mysql.VARCHAR(collation="utf8mb4_general_ci", length=50),
            nullable=True,
            comment="密码",
        ),
    )
    op.drop_column("connections", "password_encrypted")
    # ### end Alembic commands ###
