SELECT TABLE_NAME
FROM `TABLES`
WHERE TABLE_SCHEMA='serviceordercenter'
  AND TABLE_TYPE='BASE TABLE';
	
SELECT TABLE_NAME
FROM VIEWS
WHERE TABLE_SCHEMA='serviceordercenter';

SELECT ROUTINE_NAME
FROM ROUTINES
WHERE ROUTINE_SCHEMA='serviceordercenter'
  AND ROUTINE_TYPE='PROCEDURE';
	
SELECT ROUTINE_NAME
FROM ROUTINES
WHERE ROUTINE_SCHEMA='serviceordercenter'
  AND ROUTINE_TYPE='FUNCTION';


select * from tasks;

SELECT DISTINCT type FROM results;

select distinct concat('"',object_name,'",') 
  from results
  where type='function'
  and has_differences=1
  and difference_details like '%不存在%';

select distinct concat('"',object_name,'",') 
  from results
  where type='VIEW'
  and has_differences=1
  and difference_details like '%不存在%';

select distinct concat('"',object_name,'",') 
  from results
  where type='PROCEDURE'
  and has_differences=1
  and difference_details like '%不存在%';

SELECT * FROM results
WHERE type='PROCEDURE'
  AND task_log_id=48
  AND has_differences=1
  AND difference_details LIKE '%不同%';
  
__efmigrationshistory
aggregatedcounter
allnewprice
alloldprice
allprice
changhe
check_workflowjsonexclude
check_workflowjsoninfo
columnss
counter
de_carformtest
de_carformtest20200203115611815
de_carformtest20200220161521618
de_carformtest20200713171902418
de_carformtest20200826150355272
de_carformtest20200826150558295
de_carformtest20200826150611158
de_carformtest20200827092538866
de_dynamictest
de_dytest
de_dytest20200103104828588
de_dytest20200103105142537
de_dytest20200106110346264
de_dytest20200107150201507
de_dytest20200107155106276
de_dytest20200107155245825
de_remarkformdata
de_tb_merchant
de_tb_merchant01
de_tb_merchant20231129094137713
de_test002
de_test00220200514155627032
de_test1
de_testuser
de_testuser20240327101659637
de_xichashiti
de_xichashiti20220111170339908
de_xichashiti20220523150128431
df_categoryinfo
df_datadictionary
df_dataentitiesinfo
df_dataentitiesproperty
df_datasequence
df_formconfigure
df_formconfigure_id
df_formdata
df_forminfo
df_labelinfo
df_labelinfo_history
df_procedurelog
df_sequence
df_sqlinfo
df_sqlinfo_backup
df_versionsequence
df_versionsequence_backup
distributedlock
districtver1up
ehr_userinfo
hangfire_aggregatedcounter
hangfire_counter
hangfire_distributedlock
hangfire_hash
hangfire_job
hangfire_jobparameter
hangfire_jobqueue
hangfire_jobstate
hangfire_list
hangfire_server
hangfire_set
hangfire_state
job
main_prd
main_prdsite
move_workorder2023
move_workorderinfo
newprice
oldprice
order_vpsinstall
slow1114
slow1119
slow911
slow918
swj_course
swj_sc
swj_student
swj_teacher
temp_testjson
test_dynamiclocal
test_encryption
test_service_info
test_tyx
testdemo
teststruct
testuser
text_tyx2
tm_appcode
tm_commonstepinfo
tm_flowstatus
tm_ordersppayinfo
tm_panewareainfo
tm_persons
tm_persons2
tm_persons20250121
tm_persons20250212
tm_persons20250304
tm_resource
tm_userarea
tm_usermapsummary
tm_vinexport
tm_workcount_log
tm_workjsonifno
tm_workorder20250314
tmp
tmp_aes_encrypt
tmp_chpfixorder
tmp_chpresourcedetail
tmp_chprpappcode
tmp_chprporderid
tmp_csgroup
tmp_cxhis
tmp_cxhisorderid
tmp_delorderid
tmp_districtyx
tmp_districtyx1
tmp_districtyx2
tmp_districtyx3
tmp_dists
tmp_pagoodsreplaceabbreviation
tmp_tablename
tmp_tablename2
tmp_userclockininfo
tmp_vhsworkorderrecorddetail
tmp_workimp
tmp_workimp_mid
tmp_zhusuwei
workjsoninfo
z_qianyi
事务、沟通、会议任务工时明细
工作簿2
有效任务工时明细
阶段目标生产达成


vi_riskworkorderinfo_other1
vi_vhsworkedorderinfo_nojson
vi_vhsworkedorderinfo_op
vi_vhsworkingorderinfo_nojson
vi_workorderfilmdetail_2
vi_workorderlistforall_test
vi_workorderusedcarcheck2
vvi_workorderauditinfoforafc


proc_flinktest
proc_WorkflowJsonCheck_10day

fn_afcGetApprovalStatusConcat
fn_afcGetReturnedType
fn_afcgetsecondlinkrelationbyid
fn_dataversionnumber
fn_dfnextval
fn_FlowTestName
fn_FlowTestPerson
fn_FlowTestTime
fn_formversionnumber
fn_GetAcceptCodeById
fn_GetAcceptTimeById
fn_GetAFCAcceptTimeById
fn_GetAfcDispatcherCode
fn_GetAfcDispatcherName
fn_GetAFCEndVisitTimeById
fn_GetAfcLastDispatcherTimeById
fn_GetAFCLastRecordTimeById
fn_GetAFCPassAuditPersonNameById
fn_GetAFCPassAuditTimeById
fn_GetAfcRecievePromptMerits
fn_GetAfcRecieveSettleRemark
fn_GetAfcRecieveSettleTime
fn_GetAfcReturnTypeByCode
fn_GetAFCServiceAuditTimesById
fn_GetAFCSetOutTimeById
fn_GetAfcStateCycleById
fn_GetAppointById
fn_GetAppointRemarkById
fn_GetAppointStatusByCode
fn_GetAppointTime
fn_GetAscriptionByOrderId
fn_GetAscriptionNameByCode
fn_GetAssignorById
fn_GetAuditCurrentPersonInfo
fn_GetAuditStatusById
fn_GetCarBussinessTypeById
fn_GetChpAccessoriesInfo
fn_GetChpFeeApplicationInfo
fn_GetCloseStatusNameByOrderId
fn_GetConcatStrbyUserrRuleId
fn_GetCurrentPersonInfo
fn_GetCustomerAppointRemarkById
fn_GetDictNameByCode
fn_GetDictNameById
fn_GetDispatchRecordTimeById
fn_GetDispatchRemarkById
fn_GetDistrictNameByCode
fn_GetEnterRecord
fn_GetExamineTimeCust
fn_GetFeeTypeById
fn_GetFirstAppointPersonById
fn_GetFirstAppointReasonById
fn_GetFirstAppointStatusById
fn_GetFlowReturnReasonByOrderId
fn_GetGoodsNameByWorkorderId
fn_GetInstitutionNameByCode
fn_GetItemFeeById
fn_GetLastAppointChangeRemarkById
fn_GetLastAppointPersonById
fn_GetLastAppointReasonById
fn_GetLastAppointStatusById
fn_GetLastAppointStatusCodeById
fn_GetLastFailAppointConcat
fn_GetLastFailAppointReasonById
fn_GetLastRecordTimeById
fn_GetNewAppointConcat
fn_GetOldldAFCServiceAuditTimesById
fn_GetOrderNoByPrefix
fn_GetOrderReceivingStatus
fn_GetOrderTypeByCode
fn_GetQualityPerById
fn_GetReasonByOrderId
fn_GetReceiveAddRemark1
fn_GetReceiveAddRemark2
fn_GetReceiveDate
fn_GetReceiveFileNameById
fn_GetReceiveIssue
fn_GetReceivePersonAssess
fn_GetReceivePrice
fn_GetReceiveProAssess
fn_GetReceiveRegistrationDate
fn_GetReceiveStatus
fn_GetReceiveStatusRemark
fn_GetRecordCodeById
fn_GetRecordNameById
fn_GetRequestCloseById
fn_GetRequestClosePersonById
fn_GetRequestCloseTimeById
fn_GetSaleNameConcatById
fn_GetSendPersonByOrderId
fn_GetSendRemarkByOrderId
fn_GetServiceAuditAcceptTimeById
fn_GetServiceAuditFirstPersonById
fn_GetServiceAuditFirstTimeById
fn_GetServiceAuditLastPersonById
fn_GetServiceAuditLastPersonNameById
fn_GetServiceAuditLastRemarkById
fn_GetServiceAuditLastTimeById
fn_GetServiceAuditRejectReasonById
fn_GetServiceAuditRejectRemarkById
fn_GetServiceAuditTimesById
fn_GetServiceOrderStatus
fn_GetServiceSubjectNameByCode
fn_GetSpecialTagByWorkId
fn_getstaffacquisitiontaginfo
fn_GetStatusNameByCode
fn_GetStatusTypeByCode
fn_GetSubjectClassNameByCode
fn_GetSubjectNameConcat
fn_GetTaskOrderTime
fn_GetTeamNameByCode
fn_GetTimeByStatus
fn_GetTIMECHARByLoginName
fn_GetTypeCodebyId
fn_GetUserRoleConcatbyId
fn_GetVhsFileStatus
fn_GetVhsLastRecentlyChangeTime
fn_GetVhsPayStatusById
fn_GetWeekDayByNum
fn_GetWorkerInfo
fn_GetWorkFlowAcceptInfo
fn_GetWorkFlowAcceptInfonew
fn_GetWorkflowAllSteps
fn_GetWorkFlowLastPersonInfo
fn_GetWorkFlowNextTimeInfo
fn_GetWorkFlowPersonInfo
fn_GetWorkFlowPersonInfoNew
fn_GetWorkFlowPersonInforeport
fn_GetWorkFlowStartTimeInfo
fn_GetWorkFlowTimeInfo
fn_GetWorkOrderAuditTime
fn_GetWorkOrderLastDoneAt
fn_GetWorkPayStatus
fn_GetWorkTagCodeById
fn_GetWorkTime
fn_get_next_code
fn_nexbatchtval
fn_nextval
GetAscriptionByLoginName
GetChpAccessoriesInfo

